def main(x):
    import re
    wa="spends"
    wb="spent"
    w="lost"
    w1="took away"
    w2="taken away"
    w3="gives her"
    ww="gives him"
    www="gave her"
    w4="gave him"
    w5="gives away",
    w6="gave away"
    word1 = "Subtracted"
    word2 = "Deducted"
    word3 = "Reduced by"
    word4 = "Minus"
    word5 = "Decreased by"
    word6 = "Lessened by"
    word7 = "Cut by"
    word8 = "Diminished by"
    word9 = "Depleted by"
    word10 = "Withdrawn by"
    word11 = "Excluded"
    word12 = "Took away"
    word13 = "Stripped"
    word14 = "Shortened"
    word15 = "Took off"
    word16 = "Minimized"
    word17 = "Took out"
    word18 = "Shrunk"
    word19 = "Withdrawn by"
    word20 = "Diminished by"
    word21 = "Lessened by"
    word22 = "Subtracted by"
    word23 = "Depleted by"
    word24 = "Paid off"
    word25 = "Spent on"
    word26 = "Cost of"
    word27 = "Loss of"
    word28 = "Discount on"
    word29 = "Sale of"
    word30 = "Expense of"
    word31 = "Payment for"
    word32 = "Price of"
    word33 = "Value of"
    word34 = "Rate of"
    word35 = "Bill for"
    word36 = "Amount paid"
    word37 = "Decrease of"
    word38 = "Reduction of"
    word39 = "Withdrawal of"
    word40 = "Exclusion of"
    word41 = "Depletion of"
    word42 = "Minus"
    word43 = "Cut by"
    word44 = "Take off"
    word45 = "Stripped off"
    word46 = "Lowered by"
    word47 = "Discounted by"
    word48 = "Removed"
    word49 = "Reduced to"
    word50 = "Minus from"
    word51 = "Withdraw"
    word52 = "Remove"
    word53 = "Extract"
    word54 = "Exclude"
    word55 = "Omit"
    word56 = "Eliminate"
    word57 = "Subtract from"
    word58 = "Decreased to"
    word59 = "Taken away from"
    word60 = "Deduction of"
    word61 = "Discount from"
    word62 = "Loss from"
    word63 = "Elimination of"
    word64 = "Lessening of"
    word65 = "Cutting off"
    word66 = "Shrinking of"
    word67 = "Removal of"
    word68 = "Excluding"
    word69 = "Omitting"
    word70 = "Extraction of"
    word71 = "Withdrawal from"
    word72 = "Subtracting from"
    word73 = "Deducing from"
    word74 = "Discounting from"
    word75 = "Reducing from"
    word76 = "Eliminating from"
    word77 = "Loss from"
    word78 = "Removal from"
    word79 = "Deduction from"
    word80 = "Shrinking from"
    word81 = "Cutting from"
    word82 = "Lessening from"
    word83 = "Excluding from"
    word84 = "Omitting from"
    word85 = "Extraction from"
    word86 = "Withdrawal from"
    word87 = "Subtracting from"
    word88 = "Deducing from"
    word89 = "Discounting from"
    word90 = "Reducing from"
    word91 = "Eliminating from"
    word92 = "Loss from"
    word93 = "Removal from"
    word94 = "Deduction from"
    word95 = "Shrinking from"
    word96 = "Cutting from"
    word97 = "Lessening from"
    word98 = "Excluding from"
    word99 = "Omitting from"
    word100 = "Extraction from"
    wa="lends"
    wb="loses"

    # Define the variable a
    a=x

    # Define a pattern to match any of the words followed by a numeric value
    pattern = r"\b(" + "|".join(re.escape(word) for word in [w,ww,www,w1,w2,w3,w4,wa,wb,w5,w6,word1, word2,wa,wb, word3, word4, word5, word6, word7, word8, word9, word10, word11, word12, word13, word14, word15, word16, word17, word18, word19, word20, word21, word22, word23, word24, word25, word26, word27, word28, word29, word30, word31, word32, word33, word34, word35, word36, word37, word38, word39, word40, word41, word42, word43, word44, word45, word46, word47, word48, word49, word50, word51, word52, word53, word54, word55, word56, word57, word58, word59, word60,word61, word62, word63, word64, word65, word66, word67, word68, word69, word70, word71, word72, word73, word74, word75, word76, word77, word78, word79, word80, word81, word82, word83, word84, word85, word86, word87, word88, word89, word90, word91, word92, word93, word94, word95, word96, word97, word98, word99, word100]) + r")\s+(\d+)\b"

    # Use regular expression to find matches
    matches = re.findall(pattern.lower(), a.lower())

    # Print the matches
    if matches:
        for match in matches:
            word, value = match
            lis=[]
            lis.append(value)
    else:
        return 0

    result = sum(lis)
    return result